# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: micro_reddit_development
  username: aaront425
  password: PPasword1!E

test:
  <<: *default
  database: micro_reddit_test

production:
  <<: *default
  database: micro_reddit_production
  username: micro_reddit
  password: <%= ENV["MICRO_REDDIT_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
